language: python

python:
  - "3.6"

sudo: true

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10  

env:
  global:
    - PGPORT=5433

env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)

before_install:
  - sudo psql -c "ALTER USER postgres WITH PASSWORD 'postgres'" -U postgres;

install:
  - pip install -r requirements.txt

branches:
  only:
    - master

before_script:
  - cd tests
  - mkdir repo
  - git clone https://github.com/TerraME/terrame.git repo/terrame
  - git clone https://github.com/TerraME/ca.git repo/ca

script:
  - pytest -v --cov=../ecolyzer

after_success:
  - codecov -t e0ca1fb4-91fe-4111-9fb1-232f58b4e2e2
