language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

branches:
  only:
    - master

before_script:
  - cd tests
  - mkdir repo
  - git clone https://github.com/TerraME/terrame.git repo/terrame
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres'" -U postgres;

script:
  - pytest
