language: python

python:
  - "3.7"

before_install:
  - cd tests
  - mkdir repo
  - git clone https://github.com/TerraME/terrame.git repo/terrame

install:
  - pip install -r requirements.txt

script:
  - pytest
