dist: bionic

language: python

python:
  - "3.6"

addons:
  postgresql: "10"

env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install -r requirements.txt
  - pip install -r flask_ecolyzer/requirements.txt

branches:
  only:
    - master

before_script:
  - cd tests
  - mkdir repo
  - git clone https://github.com/TerraME/terrame.git repo/terrame
  - git clone https://github.com/TerraME/ca.git repo/ca
  - git clone https://github.com/jfree/jfreechart.git repo/jfreechart
  - git clone https://github.com/micromata/projectforge.git repo/projectforge
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres'" -U postgres;

script:
  - pytest -v --cov=../ecolyzer --cov=../flask_ecolyzer

after_success:
  - codecov -t e0ca1fb4-91fe-4111-9fb1-232f58b4e2e2
