language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

before_script:
  - cd tests
  - mkdir repo
  - git clone https://github.com/TerraME/terrame.git repo/terrame

script:
  - pytest
